### ISSUE TITLE
Sensor will not initiate after 0.92

### ISSUE THREAD

**Issue by bachulator** [snicker/twohunnid_ha#2]
Due this https://developers.home-assistant.io/blog/2019/04/12/new-integration-structure.html
Sensor will not initiate after home assistant upgrade >=0.92

Two additional files are necessary:

manifest.json:
{
        "domain": "zwift",
        "name": "Zwift",
        "documentation": "https://github.com/snicker/twohunnid_ha/tree/master/custom_components/zwift",
        "requirements": [],
        "dependencies": [],
        "codeowners": ["@snicker"]
}

__init__.py:
"""The zwift component."""

**Comment by snicker** [comment]
fixed and closed as of https://github.com/snicker/twohunnid_ha/commit/88923597c1d95e530a0b961dd4844a43b521935c
