### ISSUE TITLE
Compatibility with custom_component updater

### ISSUE THREAD

**Issue by bachulator** [snicker/twohunnid_ha#3]
Recently awesome people in home assistant community have created a very useful tool to automate follow up on custom components https://github.com/custom-components/custom_updater

In order to make it work the maintainer of repo should add json file to repo for change tracking. Example:
https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json

Would be coll to have similar feature for the component. Thanks!

**Comment by snicker** [comment]
Will look into this in the next few days. I've known about the custom updater for a while but have never tried it myself!

**Comment by bachulator** [comment]
Hi again @snicker,

Apparently custom_updater is old news nowadays. How about integrating Zwift sernsor to HACS https://github.com/custom-components/hacs ?

**Comment by snicker** [comment]
integrated with HACS back in september, closing issue.

https://github.com/snicker/zwift_hass
